/* Font LUT for F1012, header file
 *
 * Generated by Python on 2025-10-12T17:25:08.677662
 */
#ifndef GC9A01_FONT_H
#define GC9A01_FONT_H

#include <stdint.h>
extern const uint32_t spleenFont32[1520];
extern const uint32_t spleenFont24[1140];
extern const uint32_t spleenFont16[760];


#endif